### ISSUE TITLE
v0.1.0 Roadmap

### ISSUE THREAD

**Issue by chillcicada** [chillcicada/CcThu#1]
- [ ] base feature (Thu-Learn-Lib)
- [ ] advance feature (Thu-Info-Lib)
- [ ] log
- [ ] encrypt (offically release after completing this)
- [ ] swagger (i.e. docs)
- [ ] cron and task
- [x] auto router / response to request
  - [ ] end-to-end type safe
